[package]
name = "ed25519-bip32"
version = "0.4.3"
authors = ["Vincent Hanquez <vincent@coretype.io>", "Nicolas Di Prima <nicolas.diprima@iohk.io>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.81"
keywords = [ "ed25519-bip32", "bip32", "ed25519" ]
homepage = "https://github.com/typed-io/rust-ed25519-bip32/"
repository = "https://github.com/typed-io/rust-ed25519-bip32/"
description = "Ed25519 BIP32"
categories = [ "cryptography" ]

[dependencies]
cryptoxide = { version = "0.6", default-features = false, features = [
  "ed25519",
  "hmac",
  "sha2",
] }
zeroize = { version = "=1.8.2", default-features = false }

[features]
default = []
with-bench = []
